global:
  edition: ce
  ingress:
    annotations:
      kubernetes.io/tls-acme: true
    configureCertmanager: false
    class: traefik
    tls:
      enabled: true
  hosts:
    domain: k3d.local
  rails:
    bootsnap:
      enabled: false
  shell:
    port: 32022
certmanager:
  install: false
nginx-ingress:
  enabled: false
prometheus:
  install: false
gitlab-runner:
  install: false
gitlab:
  webservice:
    minReplicas: 1
    maxReplicas: 1
  sidekiq:
    minReplicas: 1
    maxReplicas: 1
  gitlab-shell:
    minReplicas: 1
    maxReplicas: 1
    service:
      type: NodePort
      nodePort: 32022
registry:
  hpa:
    minReplicas: 1
    maxReplicas: 1
