# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/8"

  config.vm.define "abarthelS" do |abarthelS|
    abarthelS.vm.hostname = "abarthelS"
    abarthelS.vm.network "forwarded_port", guest: 80, host: 8080
    abarthelS.vm.provider "virtualbox" do |v|
      v.memory = "512"
      v.cpus = "1"
    end
    abarthelS.vm.provision :shell, path: "server.sh"
  end

  config.vm.define "abarthelSW" do |abarthelSW|
    abarthelSW.vm.hostname = "abarthelSW"
    abarthelSW.vm.network "forwarded_port", guest: 80, host: 8080
    abarthelSW.vm.provider "virtualbox" do |v|
      v.memory = "512"
      v.cpus = "1"
    end
    abarthelSW.vm.provision :shell, path: "serverworker.sh"
  end

end
