# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_DEFAULT_PROVIDER'] = 'virtualbox'
VAGRANTFILE_API_VERSION = "2"

$k3s_script = <<-SCRIPT
curl -sfL https://get.k3s.io | sh -
SCRIPT

$k3s_server_script = <<-SCRIPT
export PATH=$PATH:/usr/local/bin/
k3s server &
SCRIPT
#cat /etc/rancher/k3s/k3s.yaml

$k3s_agent_script = <<-SCRIPT
export PATH=$PATH:/usr/local/bin/
#scp -o StrictHostKeyChecking=no root@server.k3s.local:/var/lib/rancher/k3s/server/node-token /vagrant/token
#k3s agent -s https://server.k3s.local:6443 -t $(cat /vagrant/token) --with-node-id 1
SCRIPT

def provision_instance(config, node_name, ipv4, type)
  config.vm.box = "centos/8"
  config.vm.define node_name, primary: true do |node|
    node.vm.hostname = node_name
    config.vm.provider "virtualbox" do |vb|
      vb.memory = "512"
      vb.cpus = "1"
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    end
    node.vm.network "private_network", ip: ipv4
    node.vm.provision "shell", inline: $k3s_script
    if type = "server"
      config.vm.provision "shell", inline: $k3s_server_script
    else
      config.vm.provision "shell", inline: $k3s_agent_script
    end
  end
end

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  # Server
  provision_instance(config, "abarthelS", "192.168.42.110", "server")
  # Agent
  #provision_instance(config, "abarthelSW", "192.168.42.111")
end
