apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  labels:
    app: camagru
  name: camagru
spec:
  project: camagru
  source:
    repoURL: https://github.com/Ant0wan/Camagru.git
    targetRevision: master
    path: k8s
    directory:
      recurse: true
  destination:
    server: http://argocd.k3d/
    namespace: dev
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
