---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: camagru
  labels:
    app: camagru
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Ant0wan/Camagru-deployment-abarthel.git
    targetRevision: HEAD
    path: dev
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    syncOptions:
      - CreateNamespace: true
    automated:
      selfHeal: true
      prune: true
