name: 'Terraform'
on:
  pull_request:
    paths-ignore:
      - 'README.md'
      - 'logo.png'
      - '.gitignore'
      - 'p1/*'
      - 'p2/*'
      - 'p3/confs/*'
      - 'bonus/confs/values.yaml'
  push:
    paths-ignore:
      - 'README.md'
      - 'logo.png'
      - '.gitignore'
      - 'p1/*'
      - 'p2/*'
      - 'p3/confs/*'
      - 'bonus/confs/values.yaml'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.1.2
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    - name: Terraform Format
      id: fmt
      run: terraform fmt -check

    - name: Terraform Init
      id: init
      run: terraform init

    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
